//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSBXG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutLink
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public byte[] Icon { get; set; }
        public string IconMimeType { get; set; }
        public Nullable<decimal> DispalyIndex { get; set; }
    }
}
