//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSBXG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitemap
    {
        public Sitemap()
        {
            this.Permision = new HashSet<Permision>();
            this.Document = new HashSet<Document>();
        }
    
        public string Id { get; set; }
        public string Text { get; set; }
        public string ManageUrl { get; set; }
        public string ViewUrl { get; set; }
        public Nullable<decimal> DisplayIndex { get; set; }
        public string ParentId { get; set; }
        public string ViewNeedPermission { get; set; }
    
        public virtual ICollection<Permision> Permision { get; set; }
        public virtual ICollection<Document> Document { get; set; }
    }
}
